apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: assgn2tag
  namespace: '919380639038'
  selfLink: /apis/serving.knative.dev/v1/namespaces/919380639038/services/assgn2tag
  uid: 4af9f476-2adb-4f79-a945-fc73fa731a23
  resourceVersion: AAXDU/goO7A
  generation: 4
  creationTimestamp: '2021-05-27T17:41:53.623446Z'
  labels:
    cloud.googleapis.com/location: europe-west6
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: singhals912@gmail.com
    serving.knative.dev/lastModifier: singhals912@gmail.com
    client.knative.dev/user-image: gcr.io/container-assgn2/assgn2_tag
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: assgn2tag-00004-bus
      annotations:
        run.googleapis.com/client-name: cloud-console
        client.knative.dev/user-image: gcr.io/container-assgn2/assgn2_tag
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/sandbox: gvisor
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: 919380639038-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/container-assgn2/assgn2_tag
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 4096Mi
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 4
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2021-05-27T18:31:36.582492Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2021-05-27T18:31:30.635123Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2021-05-27T18:31:36.641456Z'
  latestReadyRevisionName: assgn2tag-00004-bus
  latestCreatedRevisionName: assgn2tag-00004-bus
  traffic:
  - revisionName: assgn2tag-00004-bus
    percent: 100
    latestRevision: true
  url: https://assgn2tag-isd4ai77qq-oa.a.run.app
  address:
    url: https://assgn2tag-isd4ai77qq-oa.a.run.app
